GRASS_TERRAIN = 0
FOREST_TERRAIN = 1
HILLS_TERRAIN = 2
WATER_TERRAIN = 3
MOUNTAIN_TERRAIN = 4
SAND_TERRAIN = 5
DIRT_TERRAIN = 6
SWAMP_TERRAIN = 7
STRUCTURE_TERRAIN = 20

SPAWNPOINT = DIRT_TERRAIN

HUMAN_WARRIOR_COST = 20
UNDEAD_GHOST_COST = 10